language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: nightly

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Installing the latest C and C++ compiler versions
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++

  # Initialise Composer
  - composer self-update -q
  - composer global require hirak/prestissimo

  # Installing pickle
  - curl -L https://github.com/FriendsOfPHP/pickle/releases/download/v0.4.0/pickle.phar > ./pickle.phar

  # Installing the parle extension
  # @see http://php.net/manual/ru/book.parle.php
  - php pickle.phar install parle
  #- echo "extension=parle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Installing Composer dependencies
  - composer install --no-interaction --no-suggest --optimize-autoloader

  # Installing code coverage tools
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT format-coverage -t clover -o clover.xml

jobs:
  include:
    - stage: analysis
      script: vendor/bin/psalm

script: vendor/bin/paratest -f -p8 --coverage-clover clover.xml
